<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>PasswordManager.App</RootNamespace>
    <AssemblyName>PasswordManager</AssemblyName>
    <Version>1.0.0</Version>
    <Description>مدير كلمات المرور - Password Manager</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PasswordManager.Core\PasswordManager.Core.csproj" />
  </ItemGroup>

</Project>
